final List<Map<String, dynamic>> auctionBiddingDummyData = [
  {
    'isPinned': true,
    'isSolved': false,
    'topic': 'Lorem ipsum dolor sit',
    'author': 'Jerry',
    'replies': 245,
    'views': 3234,
    'lastPost': '12-04-2024\n2:34 PM',
    'pageNumbers': ['1', '2', '3', '4', '5', '6', '7', '8'],
  },
  {
    'isPinned': false,
    'isSolved': false,
    'topic': 'Lorem ipsum dolor sit',
    'author': 'Jerry',
    'replies': 245,
    'views': 3234,
    'lastPost': '12-04-2024\n2:34 PM',
    'pageNumbers': ['1', '2', '3', '4', '5', '6', '7', '8'],
  },
  {
    'isPinned': false,
    'isSolved': false,
    'topic': 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    'author': 'Jerry',
    'replies': 245,
    'views': 3234,
    'lastPost': '12-04-2024\n2:34 PM',
    'pageNumbers': ['1', '2', '3', '4', '5', '6', '7', '8'],
  },
  {
    'isPinned': false,
    'isSolved': true,
    'topic': 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    'author': 'Jerry',
    'replies': 245,
    'views': 3234,
    'lastPost': '12-04-2024\n2:34 PM',
    'pageNumbers': ['1', '2', '3', '4', '5', '6', '7', '8'],
  },
  {
    'isPinned': false,
    'isSolved': false,
    'topic': 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    'author': 'Jerry',
    'replies': 245,
    'views': 3234,
    'lastPost': '12-04-2024\n2:34 PM',
    'pageNumbers': ['1', '2'],
  },
  {
    'isPinned': false,
    'isSolved': false,
    'topic': 'Lorem ipsum dolor sit',
    'author': 'Jerry',
    'replies': 245,
    'views': 3234,
    'lastPost': '12-04-2024\n2:34 PM',
    'pageNumbers': ['1', '2', '3', '4'],
  },
];
